repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.1.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--allow-multiple-documents"]
      - id: check-merge-conflict
      - id: check-json

  - repo: https://github.com/asottile/reorder_python_imports
    rev: "v2.7.1"
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/PyCQA/flake8
    rev: "4.0.1"
    hooks:
      - id: flake8
        args: ["--config", "./setup.cfg"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/dhruvmanila/remove-print-statements
    rev: 'v0.3.0'
    hooks:
    - id: remove-print-statements
      args: ['--dry-run', '--verbose']

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.16.0
    hooks:
      - id: gitlint
        args: [ "--msg-filename" ]
